import { readFile, stat } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { scalarClip } from './modeling/animation.mjs'
import { importAuthoredModel } from './modeling/authored.mjs'
import { NullEngine, Scene } from './modeling/babylon.mjs'
import {
  buildArchive,
  buildArtsStudio,
  buildCouncil,
  buildDepot,
  buildEngineeringWorkshop,
  buildGarden,
  buildLibrary,
  buildReleaseGatehouse,
  buildResearchLab,
  buildReviewOffice
} from './modeling/buildings.mjs'
import { buildLeaders, buildWorkers } from './modeling/characters.mjs'
import {
  exportModel,
  injectBakedDetailTexture,
  prepareOutputDirectories,
  updateManifestStatistics,
  writeGeneratedTexture
} from './modeling/export.mjs'
import { mergeLodMeshes } from './modeling/primitives.mjs'
import { buildBus, buildTriage } from './modeling/props.mjs'
import {
  addColonyBuilderBaseline,
  addPlanetaryGround,
  addPlannedWalkways,
  buildNavigation,
  buildTerrain
} from './modeling/terrain.mjs'

// An authored (hand-modeled) GLB only replaces static geometry -- required
// animation/state channels are still code-owned data, not something the
// glTF bridge can recover (Babylon AnimationGroups never round-trip through
// a Blender export). Each entry re-attaches exactly what buildLibrary()/etc.
// would have created, targeting the same node by name.
const AUTHORED_ANIMATION_HOOKS = Object.freeze({
  library: (scene, root) => {
    const orb = scene.getTransformNodeByName('library:violet-orb')
    if (!orb) throw new Error('library authored model is missing the library:violet-orb node')
    scalarClip(scene, 'lights-idle', orb, 'rotation.y', Math.PI * 2, { duration: 100 })
    return root
  }
})

// Baked (procedurally generated by Blender's own AO bake, not hand-painted,
// not third-party) occlusion textures for authored models. Loaded once per
// build and attached to every material name listed -- same baked image
// across all of a building's approved-palette materials, since the bake
// covers one shared UV atlas spanning the whole near-LOD mesh.
const AUTHORED_TEXTURE_HOOKS = Object.freeze({
  library: {
    imagePath: fileURLToPath(new URL('./modeling/authored/library-near-ao.png', import.meta.url)),
    materials: ['bone-metal', 'lunar-rust', 'charcoal-structure', 'archive-emissive']
  },
  terrain: {
    imagePath: fileURLToPath(new URL('./modeling/authored/terrain-mixed-detail.png', import.meta.url)),
    materials: ['lunar-rust', 'charcoal-structure', 'bone-metal', 'garden-green']
  }
})

const AUTHORED_MODELS_ROOT = fileURLToPath(new URL('./modeling/authored/', import.meta.url))
const DEFAULT_OUTPUT_ROOT = fileURLToPath(new URL('../../public/lunar-city/v2/', import.meta.url))
const MANIFEST_URL = new URL('../../public/lunar-city/v2/world-manifest.v2.json', import.meta.url)
const SOURCE_REFERENCE_URL = new URL('../../public/lunar-city/v2/source-reference.v2.json', import.meta.url)
const MODEL_BUILDERS = Object.freeze({
  archive: buildArchive,
  'arts-studio': buildArtsStudio,
  bus: buildBus,
  council: buildCouncil,
  depot: buildDepot,
  'engineering-workshop': buildEngineeringWorkshop,
  garden: buildGarden,
  leaders: buildLeaders,
  library: buildLibrary,
  'release-gatehouse': buildReleaseGatehouse,
  'research-lab': buildResearchLab,
  'review-office': buildReviewOffice,
  terrain: buildTerrain,
  triage: buildTriage,
  workers: buildWorkers
})

function createScene() {
  const engine = new NullEngine({
    deterministicLockstep: true,
    lockstepMaxSteps: 4,
    renderHeight: 512,
    renderWidth: 512,
    textureSize: 512
  })
  const scene = new Scene(engine)
  scene.useRightHandedSystem = true
  return { engine, scene }
}

async function readContracts() {
  const [manifest, sourceReference] = await Promise.all([
    readFile(MANIFEST_URL, 'utf8').then(JSON.parse),
    readFile(SOURCE_REFERENCE_URL, 'utf8').then(JSON.parse)
  ])
  if (manifest.source.sha256 !== sourceReference.source.sha256) throw new Error('Lunar City source contracts disagree')
  return { manifest, sourceReference }
}

async function authoredModelPath(id) {
  const path = join(AUTHORED_MODELS_ROOT, `${id}.glb`)
  try {
    await stat(path)
    return path
  } catch {
    return null
  }
}

async function buildNavigationAsset(outputRoot) {
  const { engine, scene } = createScene()
  try {
    const root = buildNavigation(scene)
    mergeLodMeshes(scene, root, 'navigation')
    return await exportModel({
      budget: { maxDrawCalls: 4, maxGpuMiB: 4, maxMaterials: 1, maxTextures: 0, maxTriangles: 12000 },
      id: 'navigation',
      outputRoot,
      scene
    })
  } finally {
    scene.dispose()
    engine.dispose()
  }
}

export async function buildAssetPack(outputRoot = DEFAULT_OUTPUT_ROOT) {
  const { manifest, sourceReference } = await readContracts()
  await prepareOutputDirectories(outputRoot)
  const statistics = {}
  const sha256ByModel = {}
  const missing = []

  for (const model of manifest.models) {
    const build = MODEL_BUILDERS[model.id]
    if (!build) {
      missing.push(model.id)
      continue
    }
    const { engine, scene } = createScene()
    try {
      const authoredPath = await authoredModelPath(model.id)
      let root = authoredPath ? await importAuthoredModel(scene, model.id, authoredPath) : build(scene)
      if (authoredPath && model.id === 'terrain') {
        addPlanetaryGround(scene, root)
        addColonyBuilderBaseline(scene, root, { mergeMeshes: true })
        addPlannedWalkways(scene, root)
      }
      if (authoredPath && AUTHORED_ANIMATION_HOOKS[model.id]) root = AUTHORED_ANIMATION_HOOKS[model.id](scene, root)
      if (root.name !== `${model.id}:root`) throw new Error(`${model.id} builder returned ${root.name}`)
      const textureHook = AUTHORED_TEXTURE_HOOKS[model.id]
      const hasAuthoredTexture = Boolean(authoredPath && textureHook)
      statistics[model.id] = await exportModel({
        budget: model,
        id: model.id,
        outputRoot,
        scene,
        skipVertexAOSubdivision: hasAuthoredTexture
      })
      if (hasAuthoredTexture) {
        const imageBytes = await readFile(textureHook.imagePath)
        statistics[model.id] = await injectBakedDetailTexture({
          authoredPath,
          budget: model,
          extent: statistics[model.id].extent,
          id: model.id,
          imageBytes,
          materialNames: textureHook.materials,
          outputRoot
        })
      }
      sha256ByModel[model.id] = statistics[model.id].sha256
    } finally {
      scene.dispose()
      engine.dispose()
    }
  }

  const [texture, navigation] = await Promise.all([writeGeneratedTexture(outputRoot), buildNavigationAsset(outputRoot)])
  const receipt = {
    auxiliary: { navigation },
    missing,
    models: Object.keys(statistics),
    sha256ByModel,
    sourceSha256: sourceReference.source.sha256,
    statistics,
    textures: [texture]
  }
  await updateManifestStatistics(outputRoot, receipt)
  return receipt
}

async function main() {
  const outputRoot = process.argv[2] ?? DEFAULT_OUTPUT_ROOT
  const receipt = await buildAssetPack(outputRoot)
  console.log(
    JSON.stringify(
      {
        missing: receipt.missing,
        models: receipt.models,
        navigation: receipt.auxiliary.navigation.sha256,
        sha256ByModel: receipt.sha256ByModel,
        textures: receipt.textures
      },
      null,
      2
    )
  )
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main()
